var _yt_www={};(function(m){var window=this;var qa,ra;m.ba=function(a){return function(){return m.ca[a].apply(this,arguments)}};m.da=function(a){return void 0!==a};m.l=function(a,b,c){a=a.split(".");c=c||m.ea;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&m.da(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};m.n=function(a,b){for(var c=a.split("."),d=b||m.ea,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};m.fa=function(){};m.ga=function(a){a.getInstance=function(){return a.Pb?a.Pb:a.Pb=new a}};
m.ha=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};m.ia=function(a){return"array"==m.ha(a)};m.ja=function(a){var b=m.ha(a);return"array"==b||"object"==b&&"number"==typeof a.length};m.ka=function(a){return"string"==typeof a};m.ma=function(a){return"number"==typeof a};m.na=function(a){return"function"==m.ha(a)};m.oa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};m.pa=function(a){return a[qa]||(a[qa]=++ra)};
var sa=function(a,b,c){return a.call.apply(a.bind,arguments)};var ta=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};m.q=function(a,b,c){m.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?sa:ta;return m.q.apply(null,arguments)};
m.r=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};m.t=function(a,b){function c(){}c.prototype=b.prototype;a.D=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[c].apply(a,h)}};var ua=function(a){ua[" "](a);return a};m.va=function(a,b){try{return ua(a[b]),!0}catch(c){}return!1};
m.wa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,m.wa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};m.xa=function(a,b){return 0==a.lastIndexOf(b,0)};m.ya=function(a){return(0,window.encodeURIComponent)(String(a))};
m.za=function(a){if(!Aa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ba,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Da,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ea,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Fa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ga,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ha,"&#0;"));return a};m.Ia=function(a,b){return-1!=a.indexOf(b)};m.Ja=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
m.Ka=function(a,b){for(var c=0,d=(0,m.La)(String(a)).split("."),e=(0,m.La)(String(b)).split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var k=d[h]||"",p=e[h]||"",v=RegExp("(\\d*)(\\D*)","g"),y=RegExp("(\\d*)(\\D*)","g");do{var N=v.exec(k)||["","",""],aa=y.exec(p)||["","",""];if(0==N[0].length&&0==aa[0].length)break;c=Ma(0==N[1].length?0:(0,window.parseInt)(N[1],10),0==aa[1].length?0:(0,window.parseInt)(aa[1],10))||Ma(0==N[2].length,0==aa[2].length)||Ma(N[2],aa[2])}while(0==c)}return c};
var Ma=function(a,b){return a<b?-1:a>b?1:0};var Na=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;return b};m.Oa=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};m.Pa=function(a){var b=m.ka(void 0)?m.Ja(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};m.Qa=function(a,b,c){b=m.Ra(a,b,c);return 0>b?null:m.ka(a)?a.charAt(b):a[b]};
m.Ra=function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};m.Sa=function(a,b){return 0<=(0,m.Ta)(a,b)};m.Ua=function(a,b){var c=(0,m.Ta)(a,b),d;(d=0<=c)&&m.Va(a,c);return d};m.Va=function(a,b){m.Wa.splice.call(a,b,1)};m.Xa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};m.u=function(){this.hb=this.hb;this.Za=this.Za};m.Ya=function(a,b){m.Za(a,m.r(m.$a,b))};
m.Za=function(a,b){a.hb?b.call(void 0):(a.Za||(a.Za=[]),a.Za.push(m.da(void 0)?(0,m.q)(b,void 0):b))};m.$a=function(a){a&&"function"==typeof a.dispose&&a.dispose()};m.ab=function(){m.u.call(this);this.n=1;this.k=[];this.l=0;this.j=[];this.Gc={}};m.bb=function(a){cb(m.db,arguments)};m.w=function(a,b){return a in m.db?m.db[a]:b};m.x=function(a,b){m.na(a)&&(a=m.eb(a));return window.setTimeout(a,b)};m.fb=function(a,b){m.na(a)&&(a=m.eb(a));return window.setInterval(a,b)};m.gb=function(a){window.clearTimeout(a)};
m.hb=function(a){window.clearInterval(a)};m.eb=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw m.ib(b),b;}}:a};m.ib=function(a,b){var c=m.n("yt.www.errors.log");c?c(a,b):(c=m.w("ERRORS")||[],c.push([a,b]),m.bb("ERRORS",c))};m.jb=function(a){return a in m.kb};m.lb=function(a,b,c){var d=b||{};if(a=a in m.kb?m.kb[a]:c)for(var e in d)a=a.replace(new RegExp("\\$"+e,"gi"),function(){return d[e]});return a};
var cb=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};m.z=function(a,b,c){var d=mb();if(d){var e=d.subscribe(a,function(){if(!nb||nb!=e){var d=arguments,h=function(){ob[e]&&b.apply(c||window,d)};try{pb[a]?h():m.x(h,0)}catch(k){m.ib(k)}}},c);ob[e]=!0;qb[a]||(qb[a]=[]);qb[a].push(e);return e}return 0};m.rb=function(a){var b=mb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,m.A)(a,function(a){b.unsubscribeByKey(a);delete ob[a]}))};
m.B=function(a,b){var c=mb();return c?c.publish.apply(c,arguments):!1};m.sb=function(a,b){pb[a]=!0;var c=mb(),c=c?c.publish.apply(c,arguments):!1;pb[a]=!1;return c};var mb=function(){return m.n("yt.pubsub.instance_")};m.tb=function(){return!!m.n("yt.scheduler.instance")};m.ub=function(a,b){void 0===b&&(b=window.NaN);var c=m.n("yt.scheduler.instance.addJob");return c?((0,window.isNaN)(b)&&(b=0),c(a,0,b)):(0,window.isNaN)(b)?(a(),window.NaN):m.x(a,b||0)};m.vb=function(a,b){return m.ub(a,b)};
m.wb=function(a){var b=m.n("yt.scheduler.instance.cancelJob");b?b(a):m.gb(a)};m.xb=function(a){for(var b=0,c=a.length;b<c;b++)m.wb(a[b])};m.yb=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.B=d?m.eb(d):null;this.A=e?m.eb(e):null;this.n=[];this.j=this.k=0};m.zb=function(a){m.wb(a.k);a.k=m.vb((0,m.q)(a.init,a))};
m.Ab=function(a){a.name in Bb&&Cb(a.name);Bb[a.name]={reqs:[],disable:(0,m.q)(a.disable,a)};(0,m.A)(a.deps,function(b){if(!(b in Bb))throw Error("Module "+b+" required by "+a.name);Bb[b].reqs.push(a.name)});a.enable()};var Cb=function(a){if(a in Bb){var b=Bb[a];(0,m.A)(b.reqs,function(a){Cb(a)});try{b.disable()}catch(c){}delete Bb[a]}};m.Db=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};m.Fb=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};
m.Gb=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};m.Hb=function(a,b){b in a&&delete a[b]};m.Ib=function(a,b,c){if(b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};m.Jb=function(a){var b={},c;for(c in a)b[c]=a[c];return b};m.Kb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Lb.length;f++)c=Lb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var Mb=function(a){var b=arguments.length;if(1==b&&m.ia(arguments[0]))return Mb.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};m.Nb=function(){this.j="";this.k=Ob};m.Pb=function(a){return a instanceof m.Nb&&a.constructor===m.Nb&&a.k===Ob?a.j:"type_error:Const"};m.Qb=function(){this.j="";this.k=Rb};m.Sb=function(a){return a instanceof m.Qb&&a.constructor===m.Qb&&a.k===Rb?a.j:"type_error:SafeStyle"};m.Tb=function(a){var b=new m.Qb;b.j=a;return b};
m.Ub=function(){this.j="";this.k=Vb};m.Wb=function(a){return a instanceof m.Ub&&a.constructor===m.Ub&&a.k===Vb?a.j:"type_error:SafeUrl"};m.Xb=function(a){if(a instanceof m.Ub)return a;a=a.Je?a.Yd():String(a);a=Yb.test(a)?Zb(a):"about:invalid#zClosurez";var b=new m.Ub;b.j=a;return b};var Zb=function(a){try{var b=(0,window.encodeURI)(a)}catch(c){return"about:invalid#zClosurez"}return b.replace($b,function(a){return ac[a]})};var bc=function(){this.j=cc};m.dc=function(){this.j="";this.l=ec;this.k=null};
m.fc=function(a){return a instanceof m.dc&&a.constructor===m.dc&&a.l===ec?a.j:"type_error:SafeHtml"};m.gc=function(a,b,c){if(!hc.test(a))throw Error("Invalid tag name <"+a+">.");if(a.toUpperCase()in ic)throw Error("Tag name <"+a+"> is not allowed for SafeHtml.");return m.jc(a,b,c)};
m.kc=function(a){function b(a){if(m.ia(a))(0,m.A)(a,b);else{var f;a instanceof m.dc?f=a:(f=null,a.hk&&(f=a.rg()),a=m.za(a.Je?a.Yd():String(a)),f=m.lc(a,f));d+=m.fc(f);f=f.rg();0==c?c=f:0!=f&&c!=f&&(c=null)}}var c=0,d="";(0,m.A)(arguments,b);return m.lc(d,c)};m.lc=function(a,b){var c=new m.dc;c.j=a;c.k=b;return c};
m.jc=function(a,b,c){var d=null,e="<"+a;if(b)for(var f in b){if(!hc.test(f))throw Error('Invalid attribute name "'+f+'".');var h=b[f];if(null!=h){var k,p=a;k=f;if(h instanceof m.Nb)h=m.Pb(h);else if("style"==k.toLowerCase()){if(!m.oa(h))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof h+" given: "+h);if(!(h instanceof m.Qb)){var p="",v=void 0;for(v in h){if(!/^[-_a-zA-Z0-9]+$/.test(v))throw Error("Name allows only [-_a-zA-Z0-9], got: "+v);var y=
h[v];if(null!=y){if(y instanceof m.Nb)y=m.Pb(y);else if(mc.test(y)){for(var N=!0,aa=!0,la=0;la<y.length;la++){var Ca=y.charAt(la);"'"==Ca&&aa?N=!N:'"'==Ca&&N&&(aa=!aa)}N&&aa||(y="zClosurez")}else y="zClosurez";p+=v+":"+y+";"}}h=p?m.Tb(p):nc}h=m.Sb(h)}else{if(/^on/i.test(k))throw Error('Attribute "'+k+'" requires goog.string.Const value, "'+h+'" given.');if(k.toLowerCase()in oc)if(h instanceof bc)h=h instanceof bc&&h.constructor===bc&&h.j===cc?"":"type_error:TrustedResourceUrl";else if(h instanceof
m.Ub)h=m.Wb(h);else throw Error('Attribute "'+k+'" on tag "'+p+'" requires goog.html.SafeUrl or goog.string.Const value, "'+h+'" given.');}h.Je&&(h=h.Yd());k=k+'="'+m.za(String(h))+'"';e=e+(" "+k)}}null!=c?m.ia(c)||(c=[c]):c=[];!0===pc[a.toLowerCase()]?e+=">":(d=m.kc(c),e+=">"+m.fc(d)+"</"+a+">",d=d.rg());(a=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(a)?d=0:d=null);return m.lc(e,d)};m.qc=function(a,b){a.innerHTML=m.fc(b)};
m.C=function(a,b){return a?a.dataset?a.dataset[m.rc(b)]:a.getAttribute("data-"+b):null};m.sc=function(a,b){return a?a.dataset?m.rc(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};m.rc=function(a){return tc[a]||(tc[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};m.uc=function(a,b){var c=m.vc(a);window.spf.script.load(a,c,b)};
m.vc=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(wc,""),b=b.replace(xc,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};m.yc=function(a,b,c){return Math.min(Math.max(a,b),c)};m.zc=function(a,b){this.x=m.da(a)?a:0;this.y=m.da(b)?b:0};m.Ac=function(a){return m.Ia(m.Bc,a)};var Cc=function(){return m.Ac("Opera")||m.Ac("OPR")};var Dc=function(){return m.Ac("Edge")||m.Ac("Trident")||m.Ac("MSIE")};
var Ec=function(){return(m.Ac("Chrome")||m.Ac("CriOS"))&&!Cc()&&!Dc()};var Fc=function(){return m.Ac("Edge")};m.Gc=function(){return m.Ac("iPhone")&&!m.Ac("iPod")&&!m.Ac("iPad")};var Hc=function(){var a=m.Bc;if(m.Ic)return/rv\:([^\);]+)(\)|;)/.exec(a);if(m.D&&Fc())return/Edge\/([\d\.]+)/.exec(a);if(m.D)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(m.Jc)return/WebKit\/(\S+)/.exec(a)};var Kc=function(){var a=m.ea.document;return a?a.documentMode:void 0};
m.Lc=function(a){return Mc[a]||(Mc[a]=0<=m.Ka(Nc,a))};m.Oc=function(a){return m.D&&(Fc()||m.Pc>=a)};m.E=function(a){return m.ka(a)?window.document.getElementById(a):a};m.Qc=function(a){return m.ka(a)?window.document.getElementById(a):a};m.F=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=m.Rc("*",a,b)[0];return d||null};
m.Rc=function(a,b,c){var d=window.document;c=c||d;a=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},e=0,f=0,h;h=c[f];f++)a==h.nodeName&&(d[e++]=h);d.length=e;return d}return c}c=c.getElementsByTagName(a||"*");if(b){d={};for(f=e=0;h=c[f];f++)a=h.className,"function"==typeof a.split&&m.Sa(a.split(/\s+/),b)&&(d[e++]=h);d.length=e;return d}return c};
m.Sc=function(a,b){m.Db(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Tc?a.setAttribute(Tc[d],b):m.xa(d,"aria-")||m.xa(d,"data-")?a.setAttribute(d,b):a[d]=b})};m.Uc=function(a){var b=m.Vc(a);a=a.parentWindow||a.defaultView;return m.D&&m.Lc("10")&&a.pageYOffset!=b.scrollTop?new m.zc(b.scrollLeft,b.scrollTop):new m.zc(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};m.Vc=function(a){return!m.Jc&&m.Wc(a)?a.documentElement:a.body||a.documentElement};
m.Xc=function(a,b,c){return m.Yc(window.document,arguments)};m.Yc=function(a,b){var c=b[0],d=b[1];if(!Zc&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',m.za(d.name),'"');if(d.type){c.push(' type="',m.za(d.type),'"');var e={};m.Kb(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(m.ka(d)?c.className=d:m.ia(d)?c.className=d.join(" "):m.Sc(c,d));2<b.length&&m.$c(a,c,b,2);return c};
m.$c=function(a,b,c,d){function e(c){c&&b.appendChild(m.ka(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];!m.ja(f)||m.oa(f)&&0<f.nodeType?e(f):(0,m.A)(ad(f)?m.Xa(f):f,e)}};m.Wc=function(a){return"CSS1Compat"==a.compatMode};m.bd=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};m.cd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};m.dd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};
var ed=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};var fd=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};
m.gd=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};m.hd=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};var ad=function(a){if(a&&"number"==typeof a.length){if(m.oa(a))return"function"==typeof a.item||"string"==typeof a.item;if(m.na(a))return"function"==typeof a.item}return!1};
m.id=function(a,b,c,d){c||(a=a.parentNode);c=null==d;for(var e=0;a&&(c||e<=d);){if(b(a))return a;a=a.parentNode;e++}return null};m.jd=function(a){return function(){return a}};m.kd=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};m.ld=function(){};
m.md=function(a){if(a instanceof m.ld)return a;if("function"==typeof a.Fb)return a.Fb(!1);if(m.ja(a)){var b=0,c=new m.ld;c.next=function(){for(;;){if(b>=a.length)throw m.nd;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");};m.od=function(a,b,c){if(m.ja(a))try{(0,m.A)(a,b,c)}catch(d){if(d!==m.nd)throw d;}else{a=m.md(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(e){if(e!==m.nd)throw e;}}};
m.pd=function(a){if(m.ja(a))return m.Xa(a);a=m.md(a);var b=[];m.od(a,function(a){b.push(a)});return b};m.qd=function(a,b,c,d,e,f,h){var k="";a&&(k+=a+":");c&&(k+="//",b&&(k+=b+"@"),k+=c,d&&(k+=":"+d));e&&(k+=e);f&&(k+="?"+f);h&&(k+="#"+h);return k};m.rd=function(a){if(sd){sd=!1;var b=m.ea.location;if(b){var c=b.href;if(c&&(c=m.td(c))&&c!=b.hostname)throw sd=!0,Error();}}return a.match(ud)};m.vd=function(a){return a?(0,window.decodeURI)(a):a};m.td=function(a){return m.vd(m.rd(a)[3]||null)};
m.wd=function(a){a=m.rd(a);return m.qd(null,null,null,null,a[5],a[6],a[7])};m.xd=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};m.yd=function(a,b,c){if(m.ia(b))for(var d=0;d<b.length;d++)m.yd(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",m.ya(b))};var zd=function(a,b){for(var c in b)m.yd(c,b[c],a);return a};m.Ad=function(a){a=zd([],a);a[0]="";return a.join("")};
m.Bd=function(a,b){return m.xd(zd([a],b))};m.Cd=function(a,b,c){a&&(c?a&&(a=m.Xc("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),m.hd(a).body.appendChild(a)):Dd(a,b))};var Dd=function(a,b){var c=new window.Image,d=""+Ed++;Fd[d]=c;c.onload=c.onerror=function(){b&&Fd[d]&&b();delete Fd[d]};c.src=a;c=eval("null")};m.Gd=function(a,b){this.version=a;this.args=b};m.Hd=function(a,b){this.j=a;this.ve=b};
m.Id=function(a,b){var c=m.Jd();return c?c.publish.call(c,a.toString(),a,b):!1};m.Jd=function(){return m.n("yt.pubsub2.instance_")};var Kd=function(a){m.Gd.call(this,1,arguments)};m.Ld=function(a,b,c){Md(c)[a]=b||(0,m.G)();b||Nd(a);m.w("CSI_LOG_ON_TICK")&&Od(!1,c)};var Pd=function(a,b){Qd(void 0).yt_sts=a;m.Ld("_start",b,void 0)};var Rd=function(a){Sd(a);Td();m.l("yt.timing.pingSent_",!1,void 0)};
var Ud=function(a){a=Md(a);if(a.aft)return a.aft;for(var b=m.w("TIMING_AFT_KEYS",["ol"]),c=b.length,d=0;d<c;d++){var e=a[b[d]];if(e)return e}return window.NaN};
var Vd=function(a,b){var c=Wd(b).span,d;d=a.redirectEnd-a.redirectStart;0<d&&(c.rtime_=d);d=a.domainLookupEnd-a.domainLookupStart;0<d&&(c.dns_=d);d=a.connectEnd-a.connectStart;0<d&&(c.tcp_=d);d=a.connectEnd-a.secureConnectionStart;a.secureConnectionStart>=a.navigationStart&&0<d&&(c.stcp_=d);d=a.responseStart-a.requestStart;0<d&&(c.req_=d);d=a.responseEnd-a.responseStart;0<d&&(c.rcv_=d)};var Xd=function(a){return Math.round(Yd.timing.navigationStart+a)};
var Zd=function(a){var b=window.location.protocol,c=Yd.getEntriesByType("resource"),d=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.googleapis.com/css?family=")})[0],c=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});d&&0<d.startTime&&0<d.responseEnd&&(a.wfcs=Xd(d.startTime),a.wfce=Xd(d.responseEnd));c&&0<c.startTime&&0<c.responseEnd&&(a.wffs=Xd(c.startTime),a.wffe=Xd(c.responseEnd))};
var $d=function(a){var b=Md(a),c=Wd(a).span,d=Qd(a),e=m.n("yt.timing.reportbuilder_");if(e){if(e=e(b,c,d,a))ae(e),Rd(a)}else{e={v:2,s:m.w("CSI_SERVICE_NAME","youtube"),action:m.w("TIMING_ACTION")};if(Yd.now&&Yd.timing){var f=Yd.timing.navigationStart+Yd.now(),f=Math.round((0,m.G)()-f);d.yt_hrd=f}var f=m.w("TIMING_INFO")||{},h;for(h in f)d[h]=f[h];h=d.srt;delete d.srt;var k;h||0===h||(k=Yd.timing||{},h=Math.max(0,k.responseStart-k.navigationStart),(0,window.isNaN)(h)&&d.pt&&(h=d.pt));if(h||0===h)d.srt=
h;d.h5jse&&(f=window.location.protocol+m.n("ytplayer.config.assets.js"),(f=Yd.getEntriesByName?Yd.getEntriesByName(f)[0]:null)?d.h5jse=Math.round(d.h5jse-f.responseEnd):delete d.h5jse);b.aft=Ud(a);f=b._start;if("cold"==d.yt_lt){k||(k=Yd.timing||{});var p;a:if(p=k,p.msFirstPaint)p=Math.max(0,p.msFirstPaint);else{var v=window.chrome;if(v&&(v=v.loadTimes,m.na(v))){var v=v(),y=1E3*Math.min(v.requestTime||window.Infinity,v.startLoadTime||window.Infinity),y=window.Infinity===y?0:p.navigationStart-y;p=Math.max(0,
Math.round(1E3*v.firstPaintTime+y)||0);break a}p=0}0<p&&p>f&&(b.fpt=p);Vd(k,a);m.w("EXP_WEBFONT_ENABLED")&&Yd.getEntriesByType&&Zd(b)}d.p=m.w("CLIENT_PROTOCOL")||"unknown";d.t=m.w("CLIENT_TRANSPORT")||"unknown";m.w("EXP_CSI_BEACON_API")&&window.navigator.sendBeacon&&(d.ba=1);for(var N in d)"_"!=N.charAt(0)&&(e[N]=d[N]);m.w("CSI_MORE")&&(b.ps=(0,m.G)());d={};k=[];for(var aa in b)"_"!=aa.charAt(0)&&(p=Math.max(Math.round(b[aa]-f),0),d[aa]=p,k.push(aa+"."+p));e.rt=k.join(",");b={};aa=[];for(var la in c)"_"!=
la.charAt(0)&&(b[la]=c[la],aa.push(la+"."+c[la]));e.it=aa.join(",");(c=m.n("ytdebug.logTiming"))&&c(e,d,b);Rd(a);m.w("EXP_DEFER_CSI_PING")?(be(),m.l("yt.timing.deferredPingArgs_",e,void 0),a=m.x(be,0),m.l("yt.timing.deferredPingTimer_",a,void 0)):ae(e);m.Id(ce,new Kd(d.aft+(h||0)))}};var Od=function(a,b){var c=m.w("TIMING_ACTION"),d=Md(b);if(c&&d._start&&Ud(b)){var c=!0,e=m.w("TIMING_WAIT",[]);if(!a&&e.length)for(var f=0,h=e.length;f<h;++f)if(!(e[f]in d)){c=!1;break}(c||b)&&$d(b)}};
var de=function(a){m.w("CSI_LOG_ON_TICK")||Od(!1,a)};
var ae=function(a){m.w("EXP_DEFER_CSI_PING")&&(m.gb(m.n("yt.timing.deferredPingTimer_")),m.l("yt.timing.deferredPingArgs_",null,void 0));var b="https:"==window.location.protocol?"https://gg.google.com/csi":"http://csi.gstatic.com/csi",c="",d;for(d in a)c+="&"+d+"="+a[d];a=b+"?"+c.substring(1);m.w("EXP_CSI_BEACON_API")&&window.navigator.sendBeacon?window.navigator.sendBeacon&&window.navigator.sendBeacon(a)||m.Cd(a,void 0):m.Cd(a);m.l("yt.timing.pingSent_",!0,void 0)};
var be=function(a){if(m.w("EXP_DEFER_CSI_PING")){var b=m.n("yt.timing.deferredPingArgs_");b&&(a&&(b.yt_fss=a),ae(b))}};var Md=function(a){return Wd(a).tick};var Qd=function(a){return Wd(a).info};var Wd=function(a){return m.n("ytcsi."+(a||"")+"data_")||Sd(a)};var Sd=function(a){var b={tick:{},span:{},info:{}};m.l("ytcsi."+(a||"")+"data_",b,void 0);return b};var ee=function(a){m.w("CSI_MORE")&&!m.n("yt.timing.pingSent_")&&(Qd(void 0).ap=1,Qd(void 0).yt_fss=a,$d())};
var fe=function(a){a=m.ge(a);return m.he(a)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};m.he=function(a){return null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1};m.ge=function(a){a=(0,m.ie)(a);return null===a?null:a.split(".").reverse()};m.je=function(a,b){m.Cd("/gen_204?"+a,b)};m.ke=function(a){if(a.classList)return a.classList;a=a.className;return m.ka(a)&&a.match(/\S+/g)||[]};
m.H=function(a,b){return a.classList?a.classList.contains(b):m.Sa(m.ke(a),b)};m.I=function(a,b){a.classList?a.classList.add(b):m.H(a,b)||(a.className+=0<a.className.length?" "+b:b)};m.J=function(a,b){a.classList?a.classList.remove(b):m.H(a,b)&&(a.className=(0,m.le)(m.ke(a),function(a){return a!=b}).join(" "))};m.me=function(a,b,c){c?m.I(a,b):m.J(a,b)};
var ne=function(a){a=a||{};this.url=a.url||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||m.Jb(oe);this.assets=a.assets||{};this.attrs=a.attrs||m.Jb(pe);this.params=a.params||m.Jb(qe);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};m.re=function(a){a instanceof ne||(a=new ne(a));return a};var se=function(){return null!=m.te};
m.ue=function(){return m.te?m.te.invoke():null};m.ve=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,m.A)(a.childNodes,function(a){b.appendChild(m.ve(a))}):b.innerHTML=a.innerHTML;return b};
m.we=function(a){if(a=a||window.event){for(var b in a)b in xe||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;this.Wa=a;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:
a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;"MozMousePixelScroll"==this.type?(this.wheelDeltaX=a.axis==a.HORIZONTAL_AXIS?a.detail:0,this.wheelDeltaY=a.axis==a.HORIZONTAL_AXIS?0:a.detail):window.opera?(this.wheelDeltaX=0,this.wheelDeltaY=a.detail):0==a.wheelDelta%120?"WebkitTransform"in window.document.documentElement.style?window.chrome&&0==window.navigator.platform.indexOf("Mac")?(this.wheelDeltaX=a.wheelDeltaX/
-30,this.wheelDeltaY=a.wheelDeltaY/-30):(this.wheelDeltaX=a.wheelDeltaX/-1.2,this.wheelDeltaY=a.wheelDeltaY/-1.2):(this.wheelDeltaX=0,this.wheelDeltaY=a.wheelDelta/-1.6):(this.wheelDeltaX=a.wheelDeltaX/-3,this.wheelDeltaY=a.wheelDeltaY/-3);this.Hk=a.pageX;this.Ik=a.pageY}};m.ye=function(a,b,c,d){return m.Gb(m.ze,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
m.K=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=m.ye(a,b,c,d);if(e)return e;var e=++Ae.count+"",f=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),h;h=f?function(d){d=new m.we(d);if(!m.id(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new m.we(b);b.currentTarget=a;return c.call(a,b)};h=m.eb(h);m.ze[e]=[a,b,c,h,d];a.addEventListener?"mouseenter"==b&&f?a.addEventListener("mouseover",
h,d):"mouseleave"==b&&f?a.addEventListener("mouseout",h,d):"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style?a.addEventListener("MozMousePixelScroll",h,d):a.addEventListener(b,h,d):a.attachEvent("on"+b,h);return e};m.L=function(a){a&&("string"==typeof a&&(a=[a]),(0,m.A)(a,function(a){if(a in m.ze){var c=m.ze[a],d=c[0],e=c[1],f=c[3],c=c[4];d.removeEventListener?d.removeEventListener(e,f,c):d.detachEvent&&d.detachEvent("on"+e,f);delete m.ze[a]}}))};
m.Be=function(a){a=a||window.event;a=a.target||a.srcElement;3==a.nodeType&&(a=a.parentNode);return a};m.Ce=function(a){this.j=a};m.De=function(a){a=(a.j.cookie||"").split(m.Ee);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};m.Fe=function(a,b,c,d){m.Ge.set(""+a,b,c,"/",d||"youtube.com")};m.He=function(a,b){return m.Ge.get(""+a,b)};
m.Ie=function(a,b){a=!!a;m.l("_lactCookie",a,window);if(null==m.n("_lact",window)){if(m.w("EXP_LACT_TEMPDATA")){var c=(0,window.parseInt)(m.w("LACT"),10),c=(0,window.isFinite)(c)?(0,m.G)()-Math.max(c,0):-1;m.l("_lact",c,window);-1==c&&Je()}else a&&b?(c=m.He("ACTIVITY","-1"),m.l("_lact",(0,window.parseInt)(c,10),window)):(m.l("_lact",-1,window),Je());m.K(window.document,"keydown",Je);m.K(window.document,"keyup",Je);m.K(window.document,"mousedown",Je);m.K(window.document,"mouseup",Je);m.w("EXP_LACT_MOUSE")&&
m.z("page-mouse",Je);m.w("EXP_LACT_SCROLL")&&m.z("page-scroll",Je);m.w("EXP_LACT_RESIZE")&&m.z("page-resize",Je)}};var Je=function(){var a=m.n("_lact",window);null==a&&(m.Ie(),a=m.n("_lact",window));var b=(0,m.G)();m.l("_lact",b,window);m.w("EXP_LACT_TEMPDATA")||m.n("_lactCookie",window)&&1E3<=b-a&&m.Fe("ACTIVITY",""+b,-1);m.B("USER_ACTIVE")};m.Ke=function(){var a=m.n("_lact",window);return null==a?-1:Math.max((0,m.G)()-a,0)};
m.Le=function(a,b,c){var d=m.td(a);if(d==m.td(window.location.href)||!d&&m.xa(a,"/"))if(a=m.wd(a),d=a.indexOf("#"),a=0>d?a:a.substr(0,d))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&Me(a,b,c)):Me(a,b)};var Me=function(a,b,c){a=m.w("SMALLER_SESSION_TEMPDATA_NAME")?"ST-"+Na(a).toString(36):"s_tempdata-"+Na(a);c=c||5;b=b?m.Ad(b):"";m.Fe(a,b,c)};m.Ne=function(a,b,c){var d=c||"";c=window.location;a=m.Bd(a,b||{})+d;a=a instanceof m.Ub?a:m.Xb(a);c.href=m.Wb(a)};
m.Oe=function(a,b){b&&m.Le(a,b);(window.ytspf||{}).enabled?window.spf.navigate(a):m.Ne(a)};m.Pe=function(a,b,c){var d=m.w("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&m.Le(a,b);if(c)return!1;m.Oe(a);return!0};var Qe=function(a,b,c){this.A=c;this.l=a;this.n=b;this.k=0;this.j=null};var Re=function(a){m.ea.setTimeout(function(){throw a;},0)};
var Se=function(){var a=m.ea.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!m.Ac("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,m.q)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!Dc()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(m.da(c.next)){c=c.next;var a=c.qm;c.qm=null;a()}};return function(a){d.next={qm:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){m.ea.setTimeout(a,0)}};var Te=function(){this.k=this.j=null};var Ue=function(){this.next=this.scope=this.Ed=null};var Ve=function(a,b){We||Xe();Ye||(We(),Ye=!0);Ze.add(a,b)};
var Xe=function(){if(m.ea.Promise&&m.ea.Promise.resolve){var a=m.ea.Promise.resolve();We=function(){a.then($e)}}else We=function(){var a=$e;!m.na(m.ea.setImmediate)||m.ea.Window&&m.ea.Window.prototype&&m.ea.Window.prototype.setImmediate==m.ea.setImmediate?(af||(af=Se()),af(a)):m.ea.setImmediate(a)}};var $e=function(){for(var a=null;a=Ze.remove();){try{a.Ed.call(a.scope)}catch(b){Re(b)}bf.put(a)}Ye=!1};m.cf=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};
m.df=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};m.ef=function(a,b){this.j=0;this.C=void 0;this.n=this.k=this.l=null;this.A=this.B=!1;if(a==m.ff)gf(this,2,b);else try{var c=this;a.call(b,function(a){gf(c,2,a)},function(a){gf(c,3,a)})}catch(d){gf(this,3,d)}};var hf=function(){this.next=this.context=this.k=this.l=this.j=null;this.n=!1};var jf=function(a,b,c){var d=kf.get();d.l=a;d.k=b;d.context=c;return d};m.ff=function(){};
m.nf=function(a,b,c,d){a instanceof m.ef?of(a,jf(b||m.fa,c||null,d)):a.then(b,c,d)};var pf=function(a,b){if(0==a.j)if(a.l){var c=a.l;if(c.k){for(var d=0,e=null,f=null,h=c.k;h&&(h.n||(d++,h.j==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.j&&1==d?pf(c,b):(f?(d=f,d.next==c.n&&(c.n=d),d.next=d.next.next):qf(c),rf(c,e,3,b)))}a.l=null}else gf(a,3,b)};var of=function(a,b){a.k||2!=a.j&&3!=a.j||sf(a);a.n?a.n.next=b:a.k=b;a.n=b};
m.tf=function(a,b,c,d){var e=jf(null,null,null);e.j=new m.ef(function(a,h){e.l=b?function(c){try{var e=b.call(d,c);a(e)}catch(v){h(v)}}:a;e.k=c?function(b){try{var e=c.call(d,b);!m.da(e)&&b instanceof uf?h(b):a(e)}catch(v){h(v)}}:h});e.j.l=a;of(a,e);return e.j};
var gf=function(a,b,c){if(0==a.j){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(m.df(c)){a.j=1;m.nf(c,a.J,a.F,a);return}if(m.oa(c))try{var d=c.then;if(m.na(d)){vf(a,c,d);return}}catch(e){b=3,c=e}}a.C=c;a.j=b;a.l=null;sf(a);3!=b||c instanceof uf||wf(a,c)}};var vf=function(a,b,c){function d(b){f||(f=!0,a.F(b))}function e(b){f||(f=!0,a.J(b))}a.j=1;var f=!1;try{c.call(b,e,d)}catch(h){d(h)}};var sf=function(a){a.B||(a.B=!0,Ve(a.P,a))};
var qf=function(a){var b=null;a.k&&(b=a.k,a.k=b.next,b.next=null);a.k||(a.n=null);return b};var rf=function(a,b,c,d){b.j&&(b.j.l=null);if(2==c)b.l.call(b.context,d);else if(null!=b.k){if(!b.n)for(;a&&a.A;a=a.l)a.A=!1;b.k.call(b.context,d)}kf.put(b)};var wf=function(a,b){a.A=!0;Ve(function(){a.A&&xf.call(null,b)})};var uf=function(a){m.wa.call(this,a)};var yf=function(a){this.j=a;a.then((0,m.q)(function(){},this))};
var zf=function(a,b,c,d){for(var e=Array(arguments.length-3),f=3;f<arguments.length;f++)e[f-3]=arguments[f];f=Af(a,b,c).then(function(a){return a.apply(null,e)});return new yf(f)};
var Af=function(a,b,c){var d="https://www.gstatic.com/feedback/js/help/"+(a&&"prod"!=a&&"canary"!=a?"nonprod":"prod")+"/"+b;if(a=Bf[c])return a;a=(a=m.n(c))?new m.ef(m.ff,a):(new m.ef(function(a,b){var c=window.document.createElement("script");c.async=!0;c.src=d;c.onload=c.onreadystatechange=function(){c.readyState&&"loaded"!=c.readyState&&"complete"!=c.readyState||a()};c.onerror=b;(window.document.head||window.document.getElementsByTagName("head")[0]).appendChild(c)})).then(function(){var a=m.n(c);
if(!a)throw Error("Failed to load "+c+" from "+d);return a});return Bf[c]=a};var Cf=function(a,b,c){a.j.then(function(a){var e=a[b];if(!e)throw Error("Method not found: "+b);return e.apply(a,c)})};var Df=function(a){this.j=a};
var Ef=function(a,b){var c=b||{},c=zf("prod","service/lazy.min.js","help.service.Lazy.create",a,{apiKey:c.df||c.apiKey,environment:c.pf||c.environment,helpCenterPath:c.ME||c.helpCenterPath,locale:c.locale||c.locale,productData:c.XE||c.productData,receiverUri:c.YE||c.receiverUri,theme:c.theme||c.theme,window:c.window||c.window});return new Df(c)};var Ff=function(a){a=a.match(/[\d]+/g);if(!a)return"";a.length=3;return a.join(".")};var Gf=function(a){return(a=a.exec(m.Bc))?a[1]:""};
m.Hf=function(a){return 0<=m.Ka(If,a)};var Jf=function(){return m.D?m.Hf("8"):m.Kf?m.Hf("15"):m.Lf?m.Hf("5"):m.Mf};
var Nf=function(){this.l=this.k=this.j=0;this.n="";var a=m.n("window.navigator.plugins"),b=m.n("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,f=c.length;e<f;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.n=b;b=a;this.j=b[0];this.k=b[1];this.l=b[2];if(0>=this.j){var h,k,p,v;if(m.Of)try{h=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(y){h=null}else p=window.document.body,v=window.document.createElement("object"),v.setAttribute("type","application/x-shockwave-flash"),h=p.appendChild(v);if(h&&"GetVariable"in h)try{k=h.GetVariable("$version")}catch(N){k=""}p&&v&&p.removeChild(v);(h=k||"")?(h=h.split(" ")[1].split(","),
h=[(0,window.parseInt)(h[0],10)||0,(0,window.parseInt)(h[1],10)||0,(0,window.parseInt)(h[2],10)||0]):h=[0,0,0];this.j=h[0];this.k=h[1];this.l=h[2]}};var Pf=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.j>b[0]||a.j==b[0]&&a.k>b[1]||a.j==b[0]&&a.k==b[1]&&a.l>=b[2]};
var Qf=function(a){return-1<a.n.indexOf("Gnash")&&-1==a.n.indexOf("AVM2")||9==a.j&&1==a.k||9==a.j&&0==a.k&&1==a.l?!1:9<=a.j};var Rf=function(a){return m.Sf?!Pf(a,11,2):m.Tf?!Pf(a,11,3):!Qf(a)};m.Uf=function(){return m.Jc?"Webkit":m.Ic?"Moz":m.D?"ms":m.Vf?"O":null};m.Wf=function(){return m.Jc?"-webkit":m.Ic?"-moz":m.D?"-ms":m.Vf?"-o":null};m.Xf=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
m.Yf=function(a,b){return a&&b?b instanceof m.Xf?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};m.Zf=function(a,b){var c=$f[b];if(!c){var d=m.Oa(b),c=d;void 0===a.style[d]&&(d=m.Uf()+m.Pa(d),void 0!==a.style[d]&&(c=d));$f[b]=c}return c};m.ag=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};m.bg=function(a,b){a.style.height=m.ag(b,!0)};m.cg=function(a,b){a.style.display=b?"":"none"};
m.dg=function(a,b){(a=m.E(a))&&a.style&&(m.cg(a,b),m.me(a,"hid",!b))};m.M=function(a){(0,m.A)(arguments,function(a){m.dg(a,!0)})};
var eg=function(a,b){var c=m.w("FEEDBACK_LOCALE_LANGUAGE"),d=m.fg,e=m.w("FEEDBACK_LOCALE_EXTRAS",{});a?m.Kb(d,a):m.Kb(d,e);try{var f,h=m.n("yt.player.getPlayerByElement");(f=h?h("player-api"):null)&&f.pauseVideo&&f.pauseVideo();var k=Nf.getInstance();d.flashVersion=k.getVersion().join(".");f&&(d.playback_id=f.getVideoData().cpn)}catch(p){}b&&m.Kb(d,{trackingParam:b});return{helpCenterPath:"/youtube",locale:c,productData:d}};
var gg=function(){var a=m.w("SESSION_INDEX"),b=m.w("FEEDBACK_BUCKET_ID"),c={abuseLink:"https://support.google.com/youtube/bin/answer.py?answer=140536",customZIndex:"2000000005"};a&&(c.authuser=a+"");b&&(c.bucket=b);return c};m.hg=function(a,b){try{var c=(a||"59")+"",d=eg(b),e=gg();Ef(c,d).l(e);return!1}catch(f){return!0}};
m.ig=function(a,b,c,d,e,f,h,k){b=(b||"59")+"";d=eg(d,h);a={context:c,anchor:a,enableSendFeedback:f?!1:!0,defaultHelpArticleId:k};m.Kb(a,gg());try{var p=Ef(b,d);if(e&&!jg)try{p.k(a),jg=!0}catch(v){}p.n(a);return!1}catch(y){return!0}};m.kg=function(a,b,c,d){return m.ig(void 0,d,b,c,void 0,void 0,void 0,a)};m.lg=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.Re=!1;this.Hp=!0};
m.mg=function(a,b){m.lg.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.Wa=this.state=null;a&&this.init(a,b)};m.ng=function(a){return!(!a||!a[m.og])};var pg=function(a,b,c,d,e){this.Ne=a;this.j=null;this.src=b;this.type=c;this.oh=!!d;this.Sc=e;this.key=++qg;this.Mf=this.mh=!1};
var rg=function(a){a.Mf=!0;a.Ne=null;a.j=null;a.src=null;a.Sc=null};m.sg=function(a){this.src=a;this.j={};this.k=0};m.tg=function(a,b){var c=b.type;if(!(c in a.j))return!1;var d=m.Ua(a.j[c],b);d&&(rg(b),0==a.j[c].length&&(delete a.j[c],a.k--));return d};m.ug=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.Mf&&f.Ne==b&&f.oh==!!c&&f.Sc==d)return e}return-1};
m.vg=function(a,b,c,d,e){if(m.ia(b)){for(var f=0;f<b.length;f++)m.vg(a,b[f],c,d,e);return null}c=m.wg(c);return m.ng(a)?a.Q(b,c,d,e):m.xg(a,b,c,!1,d,e)};m.xg=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=!!e,k=m.yg(a);k||(a[zg]=k=new m.sg(a));c=k.add(b,c,d,e,f);if(c.j)return c;d=Ag();c.j=d;d.src=a;d.Ne=c;a.addEventListener?a.addEventListener(b.toString(),d,h):a.attachEvent(Bg(b.toString()),d);Cg++;return c};
var Ag=function(){var a=Dg,b=Eg?function(c){return a.call(b.src,b.Ne,c)}:function(c){c=a.call(b.src,b.Ne,c);if(!c)return c};return b};m.Fg=function(a){if(m.ma(a)||!a||a.Mf)return!1;var b=a.src;if(m.ng(b))return b.tq(a);var c=a.type,d=a.j;b.removeEventListener?b.removeEventListener(c,d,a.oh):b.detachEvent&&b.detachEvent(Bg(c),d);Cg--;(c=m.yg(b))?(m.tg(c,a),0==c.k&&(c.src=null,b[zg]=null)):rg(a);return!0};var Bg=function(a){return a in Gg?Gg[a]:Gg[a]="on"+a};
var Hg=function(a,b,c,d){var e=!0;if(a=m.yg(a))if(b=a.j[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.oh==c&&!f.Mf&&(f=Ig(f,d),e=e&&!1!==f)}return e};var Ig=function(a,b){var c=a.Ne,d=a.Sc||a.src;a.mh&&m.Fg(a);return c.call(d,b)};
var Dg=function(a,b){if(a.Mf)return!0;if(!Eg){var c=b||m.n("window.event"),d=new m.mg(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(h){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.currentTarget;f;f=f.parentNode)c.push(f);for(var f=a.type,k=c.length-1;!d.Re&&0<=k;k--){d.currentTarget=c[k];var p=Hg(c[k],f,!0,d),e=e&&p}for(k=0;!d.Re&&k<c.length;k++)d.currentTarget=c[k],p=Hg(c[k],f,!1,d),e=e&&p}return e}return Ig(a,
new m.mg(b,this))};m.yg=function(a){a=a[zg];return a instanceof m.sg?a:null};m.wg=function(a){if(m.na(a))return a;a[Jg]||(a[Jg]=function(b){return a.handleEvent(b)});return a[Jg]};m.Kg=function(){var a=m.He("PREF");if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(m.Lg[d]=c.toString())}};var Mg=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};
var Ng=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};m.Og=function(a){a=void 0!==m.Lg[a]?m.Lg[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};m.Pg=function(a,b){return!!((m.Og("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
var Qg=function(a,b,c){if(b){a=m.ka(a)?m.Qc(a):a;c=m.re(c);var d=m.Jb(c.attrs);d.tabindex=0;var e=m.Jb(c.params);e.flashvars=m.Ad(c.args);if(m.Of){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var f in d)b.setAttribute(f,d[f]);for(f in e)d=window.document.createElement("param"),d.setAttribute("name",f),d.setAttribute("value",e[f]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");
b.setAttribute("name",d.id);for(f in d)b.setAttribute(f,d[f]);for(f in e)b.setAttribute(f,e[f])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};m.Rg=function(a,b){a=m.ka(a)?m.Qc(a):a;b=m.re(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=Nf.getInstance();Pf(c,b.minVersion)?(c=Sg(b,c),Qg(a,c,b)):Tg(a,b,c)};
var Ug=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=m.re(a);var d=!!b,e=m.E(a.attrs.id),f=e?e.parentNode:null;if(e&&f){if(window!=window.top){var h=null;if(window.document.referrer){var k=window.document.referrer.substring(0,128);fe(k)||(h=k)}else h="unknown";h&&(d=!0,a.args.framer=h)}h=Nf.getInstance();if(Pf(h,a.minVersion)){var k=Sg(a,h),p="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(p=e.getAttribute("src")||e.movie);(p!=k||d)&&Qg(f,k,a);Rf(h)&&Vg()}else Tg(f,a,h);c&&c()}else m.x(function(){Ug(a,
b,c)},50)}};var Tg=function(a,b,c){0==c.j&&b.fallback?b.fallback():0==c.j&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+m.lb("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};var Sg=function(a,b){var c;(c=Qf(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!Pf(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.url};
var Vg=function(){var a=m.E("flash10-promo-div"),b=m.Pg(m.Kg.getInstance(),107);a&&!b&&m.M(a)};m.Wg=function(a,b){var c=a.match(Xg);window.spf.style.load(a,c?c[1]:"",b)};var Yg=function(){if(2.2==Zg)return!0;var a;a=m.n("yt.player.utils.videoElement_");a||(a=window.document.createElement("video"),m.l("yt.player.utils.videoElement_",a,void 0));try{return!(!a||!a.canPlayType||!a.canPlayType('video/mp4; codecs="avc1.42001E, mp4a.40.2"')&&!a.canPlayType('video/webm; codecs="vp8.0, vorbis"'))}catch(b){return!1}};
var $g=function(){};m.ah=function(){};m.bh=function(a){this.j=a};m.ch=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.j=a};var dh=function(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.j=a};
m.eh=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};m.fh=function(a){return(new m.gh(void 0)).yb(a)};m.gh=function(a){this.j=a};
var hh=function(a,b,c){switch(typeof b){case "string":ih(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(m.ia(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],hh(a,a.j?a.j.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&
(c.push(d),ih(f,c),c.push(":"),hh(a,a.j?a.j.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}};var ih=function(a,b){b.push('"',a.replace(jh,function(a){if(a in kh)return kh[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return kh[a]=e+b.toString(16)}),'"')};m.lh=function(a){this.j=a};var mh=function(a){this.j=a};var nh=function(a){this.data=a};var oh=function(a){return!m.da(a)||a instanceof nh?a:new nh(a)};
m.ph=function(a){this.j=a};m.qh=function(a){var b=a.creation;a=a.expiration;return!!a&&a<(0,m.G)()||!!b&&b>(0,m.G)()};m.rh=function(a){this.j=a};m.sh=function(a,b,c){var d=c&&0<c?c:0;c=d?(0,m.G)()+1E3*d:0;if((d=d?m.th:m.uh)&&window.JSON){m.ka(b)||(b=JSON.stringify(b,void 0));try{d.set(a,b,c)}catch(e){d.remove(a)}}};m.vh=function(a){if(!m.uh&&!m.th||!window.JSON)return null;var b;try{b=m.uh.get(a)}catch(c){}if(!m.ka(b))try{b=m.th.get(a)}catch(d){}if(!m.ka(b))return null;try{b=JSON.parse(b,void 0)}catch(e){}return b};
var wh=function(){var a={volume:100,muted:!1},b=m.vh("yt-player-volume")||{};a.volume=(0,window.isNaN)(b.volume)?100:m.yc(b.volume,0,100);a.muted=void 0==b.muted?!1:b.muted;return a};
var xh=function(a,b){m.u.call(this);this.n=this.B=a;this.S=b;this.P=!1;this.k={};this.$a=this.O=null;this.ga=new m.ab;m.Ya(this,this.ga);this.A={};this.J=this.ab=this.l=this.Eb=this.j=null;this.Fa=!1;this.R=this.F=this.vb=this.C=null;this.ib={};this.rd=["onReady"];this.mb=[];this.Lb=null;this.ic=0;this.Pa={};yh(this);this.nd("onVolumeChange",(0,m.q)(this.ky,this));this.nd("onError",(0,m.q)(this.iy,this));this.nd("onTabOrderChange",(0,m.q)(this.as,this));this.nd("onTabAnnounce",(0,m.q)(this.yA,this));
this.nd("WATCH_LATER_VIDEO_ADDED",(0,m.q)(this.ly,this));this.nd("WATCH_LATER_VIDEO_REMOVED",(0,m.q)(this.my,this));this.nd("onMouseWheelCapture",(0,m.q)(this.Zx,this));this.nd("onMouseWheelRelease",(0,m.q)(this.$x,this));this.nd("onMouseMoveCapture",(0,m.q)(this.Xx,this));this.ub=!1;this.Hc=m.Mf||m.Kf;this.Ra=this.U=null;m.vg(this.B,"mousewheel",this.To,!1,this);m.vg(this.B,"wheel",this.To,!1,this)};
var zh=function(a,b){a.Eb=b;a.j=b.clone();a.l=a.j.attrs.id||a.l;"video-player"==a.l&&(a.l=a.S,a.j.attrs.id=a.S);a.n.id==a.l&&(a.l=a.l+"-player",a.j.attrs.id=a.l);a.j.args.enablejsapi="1";a.j.args.playerapiid=a.S;a.ab||(a.ab=Ah(a,a.j.args.jsapicallback||"onYouTubePlayerReady"));a.j.args.jsapicallback=null;var c=a.j.attrs.width;c&&(a.n.style.width=m.ag(Number(c)||c,!0));(c=a.j.attrs.height)&&m.bg(a.n,Number(c)||c);a.n.style.overflow="hidden"};
var Bh=function(a){a.j.loaded||(a.j.loaded=!0,"0"!=a.j.args.autoplay?a.k.loadVideoByPlayerVars(a.j.args):a.k.cueVideoByPlayerVars(a.j.args))};var Ch=function(a){if(!m.da(a.j.disable.flash)){var b=a.j.disable,c;c=Pf(Nf.getInstance(),a.j.minVersion);b.flash=!c}return!a.j.disable.flash};
var Dh=function(a){var b=Eh(a);b&&b.stopVideo&&b.stopVideo();if(Ch(a)){var c=a.j;b&&b.getUpdatedConfigurationData&&(c=m.re(b.getUpdatedConfigurationData()));c.args.autoplay=1;c.args.html5_unavailable="1";zh(a,c);Fh(a,"flash")}};
var Fh=function(a,b){if(!a.Na()){if(!b){var c;if(!(c=!a.j.html5&&Ch(a))){if(!m.da(a.j.disable.html5)){if(c=Yg())c=Gh(a)||a.j.assets.js;a.j.disable.html5=!c;c||(a.j.args.html5_unavailable="1")}c=!!a.j.disable.html5}b=c?Ch(a)?"flash":"unsupported":"html5"}("flash"==b?a.RA:"html5"==b?a.SA:a.TA).call(a)}};var Gh=function(a){var b=!0,c=Eh(a);c&&a.j&&(a=a.j,b=m.C(c,"version")==a.assets.js);return b&&!!m.n("yt.player.Application.create")};
var Eh=function(a){var b=m.E(a.l);!b&&a.n&&a.n.querySelector&&(b=a.n.querySelector("#"+a.l));return b};var Hh=function(a,b,c){var d=b[c];return function(){try{return a.Lb=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&"sendAbandonmentPing"!=c&&(e.message+=" ("+c+")",a.Lb=e,m.ib(e,"WARNING"))}}};
var yh=function(a){a.P=!1;if(a.$a)for(var b in a.A)a.$a(b,a.A[b]);for(var c in a.Pa)m.gb((0,window.parseInt)(c,10));a.Pa={};a.O=null;a.$a=null;for(var d in a.k)a.k[d]=null;a.k.addEventListener=(0,m.q)(a.nd,a);a.k.removeEventListener=(0,m.q)(a.Qz,a);a.k.destroy=(0,m.q)(a.dispose,a);a.k.getLastError=(0,m.q)(a.Ks,a);a.k.getPlayerType=(0,m.q)(a.Ls,a);a.k.getCurrentVideoConfig=(0,m.q)(a.Js,a);a.k.loadNewVideoConfig=(0,m.q)(a.Hl,a);a.k.isReady=(0,m.q)(a.eB,a)};
var Ah=function(a,b){var c=b;if("string"==typeof b){if(a.ib[b])return a.ib[b];c=function(){var a=m.n(b);a&&a.apply(m.ea,arguments)};a.ib[b]=c}return c?c:null};var Ih=function(a,b){var c="ytPlayer"+b+a.S;a.A[b]=c;m.ea[c]=function(c){var e=m.x(function(){a.Na()||(a.ga.W(b,c),m.Hb(a.Pa,String(e)))},0);m.Ib(a.Pa,String(e),!0)};return c};var Jh=function(a){return(a=Eh(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
var Kh=function(a){m.Ld("dcp");a.cancel();yh(a);a.J=null;a.j&&(a.j.loaded=!1);var b=Eh(a);"html5"==Jh(a)?a.vb=b:b&&b.destroy&&b.destroy();m.bd(a.B);m.L(a.mb);a.mb.length=0;a.F=null;a.R=null};m.Lh=function(a,b){a=m.ka(a)?m.Qc(a):a;b=m.re(b);var c=Mh+"_"+m.pa(a),d=Nh[c];if(d)return d.Hl(b),d.k;d=new xh(a,c);Nh[c]=d;m.B("player-added",d.k);m.Za(d,m.r(Oh,d));m.x(function(){d.Hl(b)},0);return d.k};var Ph=function(){for(var a in Nh){var b=Nh[a];b&&b.cancel()}};
m.Qh=function(a){if(a=m.E(a))a=Mh+"_"+m.pa(a),(a=Nh[a])&&a.dispose()};var Oh=function(a){Nh[a.getId()]=null};m.Rh=function(a){a=m.E(a);if(!a)return null;var b=Mh+"_"+m.pa(a),c=Nh[b];c||(c=new xh(a,b),Nh[b]=c);return c.k};m.Sh=function(){return m.H(m.E("page-container"),"remote-connected")};
var Th=function(){m.l("yt.abuse.botguardInitialized",se,void 0);m.l("yt.abuse.invokeBotguard",m.ue,void 0);m.l("yt.player.exports.navigate",m.Pe,void 0);m.l("yt.player.embed",m.Lh,void 0);m.l("yt.player.destroy",m.Qh,void 0);m.l("yt.player.cancelAll",Ph,void 0);m.l("yt.player.getPlayerByElement",m.Rh,void 0);m.l("yt.player.exports.feedbackStart",m.hg,void 0);m.l("yt.player.exports.feedbackShowArticle",m.kg,void 0);m.l("yt.util.activity.init",m.Ie,void 0);m.l("yt.util.activity.getTimeSinceActive",
m.Ke,void 0);m.l("yt.util.activity.setTimestamp",Je,void 0);var a=m.n("ytplayer.config");Uh(a);m.n("ytspf.enabled")&&(Vh=m.fb(Wh,5E3),(a=m.Xh())?(a.addEventListener("onReady",Wh),a.addEventListener("onStateChange",Wh)):Yh("unable to init PP monitor"))};
var Uh=function(a){Ph();if(a=a||null){var b=m.Xh(),c=!0,d=m.Zh;m.Zh=null;b&&b.getVideoData&&d&&(c=b.getVideoData(),c=!!d.fullscreen||c.video_id!=a.args.video_id||c.list!=a.args.list||c.video_id!=d.videoId||c.list!=d.listId);c?($h="",m.Lh("player-api",a)):b.playVideo();a=m.re(a);a.loaded=!0}Wh();m.l("ytplayer.config",a,void 0)};m.Xh=function(){var a=m.n("yt.player.getPlayerByElement");return a?a("player-api"):null};
var Wh=function(){var a=m.Xh();if(a){var b;b=m.E("player");b=!b||m.H(b,"off-screen");var c=1==(a&&a.isReady()?a.getPlayerState():void 0),d="watch"==m.w("PAGE_NAME"),e=m.Sh();!c||d||e||(Yh("PP playing off watch (paused)"),a.pauseVideo());b&&d?Yh("PP off-screen on watch"):b||d||Yh("PP !off-screen off watch")}};var Yh=function(a){var b=m.w("PAGE_NAME");b&&(b=[b,$h,m.n("_spf_state.nav-counter")],a+="("+b.join(",")+")",m.l("yt.www.persistentplayer.issue",a,void 0),m.ib(Error(a),"WARNING"))};
var ai=function(){m.Ld("ol");bi("init");var a=m.w("PAGE_NAME");a&&bi("init-"+a);de()};var bi=function(a){m.tb()?ci.push(m.ub(m.r(m.sb,a),0)):m.B(a)};var di=function(){m.xb(ci);ci.length=0;var a=m.w("PAGE_NAME");a&&m.sb("dispose-"+a);m.sb("dispose")};var ei=function(){ai()};var fi=function(){m.w("TIMING_REPORT_ON_UNLOAD")&&Od(!0);ee("u");be("u");di()};
var gi=function(a,b,c,d,e){for(var f=window.document.getElementsByTagName("script"),h=!1,k=0,p=f.length;k<p;k++)if(0<f[k].src.indexOf("/debug-")){h=!0;break}h&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),m.ib(e))};var hi=function(){ii=1;ji=0;m.w("TIMING_REPORT_ON_UNLOAD")&&Od(!0);ee("n");be("n");Rd();m.w("CSI_TRACK_ON_BEGIN")&&Pd("nb");Nd("mark_navigation_requested");ki(li);m.sb("navigate")};
var mi=function(a){a=a.detail.part||a.detail.partial;m.Ld("nc"+ji);++ji;var b=1==ii;ii=2;b?(ki(ni),oi()):ki(pi);(a=a.data&&a.data.swfcfg)&&qi(a)};var ri=function(){};var si=function(a){a=a.detail.response;var b=1==ii;ii=3;b&&(ki(ti),oi());(a=a.data&&a.data.swfcfg)&&qi(a)};
var ui=function(a){m.Ld("nd");a=a.detail.response;m.vi=a.cacheKey;a=a.timing;var b=window._spf_state,b=b&&b["nav-counter"]||0;Qd(void 0).yt_nav=b;Pd("ne",a.responseStart);b=Math.max(0,a.responseStart-a.navigationStart);Qd(void 0).srt=b;b=a.spfCached?"hot":"warm";Qd(void 0).yt_lt=b;b=+!!a.spfPrefetched;Qd(void 0).yt_pft=b;b=a.responseStart-a.fetchStart;Wd(void 0).span.req=b;"redirectStart"in a&&Vd(a);ki(wi);window.document.getElementById("content").style.height="";ai();ii=0};
var xi=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),m.ib(a)};var yi=function(a){a=m.Ad({spfreload:"1",url:a.detail.url,reason:a.detail.reason});m.je(a)};var zi=function(){Ai()};var Bi=function(){};
var oi=function(){m.w("USE_SPF_SCROLL_POSITION")||window.scroll(0,0);var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");di();for(var b in m.db)delete m.db[b];m.l("ytplayer.config",null,void 0);if((a=m.Xh())&&a.stopVideo){if(a.stopVideo(),a=a.getLastError())$h=a,(a=m.E("movie_player"))&&a.stopVideo?(a.stopVideo(),$h="recovered"):$h="missing2"}else $h="missing";Wh()};var qi=function(a){"cfg"in Md(void 0)||m.Ld("cfg");Uh(a)};
var ki=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.appendChild(window.document.createElement("dt")),b.appendChild(window.document.createElement("dd")),window.document.body.appendChild(b));m.wb(Ci);Ci=m.vb(function(){var c=a[0],d=a[1],e=a[2];b.className="";var f=b.style;f.transitionDuration=f.webkitTransitionDuration=c+"ms";f.width=d+"%";m.gb(Di);Di=m.x(function(){b.className=e},c)},0)};
var Ai=function(){var a=wi[0]+50;m.gb(Di);Di=m.x(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};var Ei=function(){m.yb.call(this,"www/base");this.l=0};var Fi=function(a){(a=a.detail.name)&&Cb(a)};m.ca=[];m.Gi=m.Gi||{};m.ea=this;qa="closure_uid_"+(1E9*Math.random()>>>0);ra=0;m.G=Date.now||function(){return+new Date};
Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return m.q.apply(null,c)}return(0,m.q)(this,a)};ua[" "]=m.fa;m.t(m.wa,Error);m.wa.prototype.name="CustomError";var Ba,Da,Ea,Fa,Ga,Ha,Aa;m.La=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};Ba=/&/g;Da=/</g;Ea=/>/g;Fa=/"/g;Ga=/'/g;Ha=/\x00/g;Aa=/[\x00&<>"']/;m.Hi=2147483648*Math.random()|0;m.Wa=Array.prototype;m.Ta=m.Wa.indexOf?function(a,b,c){return m.Wa.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(m.ka(a))return m.ka(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
m.Ii=m.Wa.lastIndexOf?function(a,b,c){return m.Wa.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(m.ka(a))return m.ka(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};m.A=m.Wa.forEach?function(a,b,c){m.Wa.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
m.le=m.Wa.filter?function(a,b,c){return m.Wa.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=m.ka(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var p=h[k];b.call(c,p,k,a)&&(e[f++]=p)}return e};m.Ji=m.Wa.map?function(a,b,c){return m.Wa.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=m.ka(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};
m.Ki=m.Wa.reduce?function(a,b,c,d){d&&(b=(0,m.q)(b,d));return m.Wa.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,m.A)(a,function(c,h){e=b.call(d,e,c,h,a)});return e};m.Li=m.Wa.some?function(a,b,c){return m.Wa.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};
m.Mi=m.Wa.every?function(a,b,c){return m.Wa.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};m.u.prototype.hb=!1;m.u.prototype.Na=function(){return this.hb};m.u.prototype.dispose=function(){this.hb||(this.hb=!0,this.L())};m.u.prototype.L=function(){if(this.Za)for(;this.Za.length;)this.Za.shift()()};m.t(m.ab,m.u);m.g=m.ab.prototype;m.g.subscribe=function(a,b,c){var d=this.Gc[a];d||(d=this.Gc[a]=[]);var e=this.n;this.j[e]=a;this.j[e+1]=b;this.j[e+2]=c;this.n=e+3;d.push(e);return e};m.g.Ye=function(a,b,c){if(a=this.Gc[a]){var d=this.j;if(a=m.Qa(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.tc(a)}return!1};m.g.tc=function(a){if(0!=this.l)return this.k.push(a),!1;var b=this.j[a];if(b){var c=this.Gc[b];c&&m.Ua(c,a);delete this.j[a];delete this.j[a+1];delete this.j[a+2]}return!!b};
m.g.W=function(a,b){var c=this.Gc[a];if(c){this.l++;for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];e=0;for(f=c.length;e<f;e++){var h=c[e];this.j[h+1].apply(this.j[h+2],d)}this.l--;if(0<this.k.length&&0==this.l)for(;c=this.k.pop();)this.tc(c);return 0!=e}return!1};m.g.clear=function(a){if(a){var b=this.Gc[a];b&&((0,m.A)(b,this.tc,this),delete this.Gc[a])}else this.j.length=0,this.Gc={}};m.g.Xa=m.ba(3);
m.g.L=function(){m.ab.D.L.call(this);this.clear();this.k.length=0};m.db=window.yt&&window.yt.config_||window.ytcfg&&window.ytcfg.data_||{};m.l("yt.config_",m.db,void 0);m.l("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);m.kb=window.yt&&window.yt.msgs_||{};m.l("yt.msgs_",m.kb,void 0);m.Of="Microsoft Internet Explorer"==window.navigator.appName;var Ni=m.n("yt.pubsub.instance_")||new m.ab;m.ab.prototype.subscribe=m.ab.prototype.subscribe;m.ab.prototype.unsubscribeByKey=m.ab.prototype.tc;m.ab.prototype.publish=m.ab.prototype.W;m.ab.prototype.clear=m.ab.prototype.clear;m.l("yt.pubsub.instance_",Ni,void 0);var ob=m.n("yt.pubsub.subscribedKeys_")||{};m.l("yt.pubsub.subscribedKeys_",ob,void 0);var qb=m.n("yt.pubsub.topicToKeys_")||{};m.l("yt.pubsub.topicToKeys_",qb,void 0);var pb=m.n("yt.pubsub.isSynchronous_")||{};
m.l("yt.pubsub.isSynchronous_",pb,void 0);var nb=m.n("yt.pubsub.skipSubId_")||null;m.l("yt.pubsub.skipSubId_",nb,void 0);m.g=m.yb.prototype;m.g.Xz=function(){2==this.j||this.init()};m.g.enable=function(){this.j=1;(0,m.A)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.Xz,this),this.subscribe("dispose-"+a,this.dispose,this),m.w("PAGE_NAME")==a&&m.zb(this))},this)};m.g.init=function(){m.wb(this.k);this.j=2;this.B&&this.B()};m.g.dispose=function(){this.j=3;m.wb(this.k);this.A&&this.A()};m.g.disable=function(){this.j=4;this.clear();try{this.dispose()}catch(a){m.ib(a)}};
m.g.subscribe=function(a,b,c){a=m.z(a,b,c);this.n.push(a);return a};m.g.clear=function(){m.rb(this.n);this.n=[]};var Bb=m.n("yt.modules.registry_")||{};m.l("yt.modules.registry_",Bb,void 0);var Lb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");var pc=Mb("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));m.Oi=RegExp("^[^\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");m.Pi=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");m.Nb.prototype.Je=!0;m.Nb.prototype.Yd=function(){return this.j};m.Nb.prototype.toString=function(){return"Const{"+this.j+"}"};var Ob={};m.Qb.prototype.Je=!0;var Rb={};m.Qb.prototype.Yd=function(){return this.j};var nc=m.Tb(""),mc=/^[-,."'%_!# a-zA-Z0-9]+$/;m.Ub.prototype.Je=!0;m.Ub.prototype.Yd=function(){return this.j};m.Ub.prototype.hk=!0;m.Ub.prototype.rg=function(){return 1};var Yb=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i,$b=/[()']|%5B|%5D|%25/g,ac={"'":"%27","(":"%28",")":"%29","%5B":"[","%5D":"]","%25":"%"},Vb={};bc.prototype.Je=!0;bc.prototype.Yd=function(){return""};bc.prototype.hk=!0;bc.prototype.rg=function(){return 1};var cc={};var hc,oc,ic,ec;m.dc.prototype.hk=!0;m.dc.prototype.rg=function(){return this.k};m.dc.prototype.Je=!0;m.dc.prototype.Yd=function(){return this.j};hc=/^[a-zA-Z0-9-]+$/;oc={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0};ic={EMBED:!0,IFRAME:!0,LINK:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,TEMPLATE:!0};ec={};m.Qi=m.lc("<!DOCTYPE html>",0);m.Ri=m.lc("",0);var tc={};var wc=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,xc=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;m.g=m.zc.prototype;m.g.clone=function(){return new m.zc(this.x,this.y)};m.g.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};m.g.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};m.g.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};m.g.scale=function(a,b){var c=m.ma(b)?b:a;this.x*=a;this.y*=c;return this};a:{var Si=m.ea.navigator;if(Si){var Ti=Si.userAgent;if(Ti){m.Bc=Ti;break a}}m.Bc=""};var Vi,Nc,Mc,Zi,$i;m.Vf=Cc();m.D=Dc();m.Ic=m.Ac("Gecko")&&!(m.Ia(m.Bc.toLowerCase(),"webkit")&&!Fc())&&!(m.Ac("Trident")||m.Ac("MSIE"))&&!Fc();m.Jc=m.Ia(m.Bc.toLowerCase(),"webkit")&&!Fc();m.Jc&&m.Ac("Mobile");m.Tf=m.Ac("Macintosh");m.Sf=m.Ac("Windows");m.Ui=m.Ac("Linux")||m.Ac("CrOS");Vi=m.ea.navigator||null;Vi&&m.Ia(Vi.appVersion||"","X11");m.Wi=m.Ac("Android");m.Xi=m.Gc();m.Yi=m.Ac("iPad");
Nc=function(){if(m.Vf&&m.ea.opera){var a=m.ea.opera.version;return m.na(a)?a():a}var a="",b=Hc();b&&(a=b?b[1]:"");return m.D&&!Fc()&&(b=Kc(),b>(0,window.parseFloat)(a))?String(b):a}();Mc={};Zi=m.ea.document;$i=Kc();m.Pc=!Zi||!m.D||!$i&&Fc()?void 0:$i||("CSS1Compat"==Zi.compatMode?(0,window.parseInt)(Nc,10):5);var Zc;Zc=!m.D||m.Oc(9);m.aj=!m.Ic&&!m.D||m.D&&m.Oc(9)||m.Ic&&m.Lc("1.9.1");m.bj=m.D&&!m.Lc("9");m.cj=m.D||m.Vf||m.Jc;m.dj=m.D&&!m.Oc(9);var Tc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};m.ej=m.jd(!1);m.fj=m.jd(!0);m.gj=m.jd(null);m.nd="StopIteration"in m.ea?m.ea.StopIteration:Error("StopIteration");m.ld.prototype.next=function(){throw m.nd;};m.ld.prototype.Fb=function(){return this};var ud=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,sd=m.Jc;var Fd={},Ed=0,hj=m.n("yt.net.ping.workerUrl_")||null;m.l("yt.net.ping.workerUrl_",hj,void 0);m.Gd.prototype.yb=function(){return{version:this.version,args:this.args}};m.Hd.prototype.toString=function(){return this.j};var ij=m.n("yt.pubsub2.instance_")||new m.ab;m.ab.prototype.subscribe=m.ab.prototype.subscribe;m.ab.prototype.unsubscribeByKey=m.ab.prototype.tc;m.ab.prototype.publish=m.ab.prototype.W;m.ab.prototype.clear=m.ab.prototype.clear;m.l("yt.pubsub2.instance_",ij,void 0);m.jj=m.n("yt.pubsub2.subscribedKeys_")||{};m.l("yt.pubsub2.subscribedKeys_",m.jj,void 0);m.kj=m.n("yt.pubsub2.topicToKeys_")||{};m.l("yt.pubsub2.topicToKeys_",m.kj,void 0);m.lj=m.n("yt.pubsub2.isAsync_")||{};
m.l("yt.pubsub2.isAsync_",m.lj,void 0);m.l("yt.pubsub2.skipSubKey_",null,void 0);m.t(Kd,m.Gd);var ce=new m.Hd("timing-sent",Kd);var Yd=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{},Td=(0,m.q)(Yd.clearResourceTimings||Yd.webkitClearResourceTimings||Yd.mozClearResourceTimings||Yd.msClearResourceTimings||Yd.oClearResourceTimings||m.fa,Yd),Nd=Yd.mark?function(a){Yd.mark(a)}:m.fa;m.ie=m.td;var oe={enablejsapi:1},pe={},qe={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};ne.prototype.clone=function(){var a=new ne,b;for(b in this){var c=this[b];"object"==m.ha(c)?a[b]=m.Jb(c):a[b]=c}return a};m.te=null;m.mj=m.Jc?"webkit":m.Ic?"moz":m.D?"ms":m.Vf?"o":"";m.nj=m.n("yt.dom.getNextId_");if(!m.nj){m.nj=function(){return++oj};m.l("yt.dom.getNextId_",m.nj,void 0);var oj=0};m.g=m.we.prototype;m.g.Wa=null;m.g.type="";m.g.target=null;m.g.relatedTarget=null;m.g.currentTarget=null;m.g.data=null;m.g.source=null;m.g.state=null;m.g.keyCode=0;m.g.charCode=0;m.g.altKey=!1;m.g.ctrlKey=!1;m.g.shiftKey=!1;m.g.clientX=0;m.g.clientY=0;m.g.wheelDeltaX=0;m.g.wheelDeltaY=0;m.g.rotation=0;m.g.scale=1;m.g.touches=null;m.g.changedTouches=null;m.g.preventDefault=function(){this.Wa.returnValue=!1;this.Wa.preventDefault&&this.Wa.preventDefault()};
m.g.stopPropagation=function(){this.Wa.cancelBubble=!0;this.Wa.stopPropagation&&this.Wa.stopPropagation()};m.g.stopImmediatePropagation=function(){this.Wa.cancelBubble=!0;this.Wa.stopImmediatePropagation&&this.Wa.stopImmediatePropagation()};var xe={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1};m.ze=m.n("yt.events.listeners_")||{};m.l("yt.events.listeners_",m.ze,void 0);var Ae=m.n("yt.events.counter_")||{count:0};m.l("yt.events.counter_",Ae,void 0);m.Ee=/\s*;\s*/;m.g=m.Ce.prototype;m.g.isEnabled=function(){return window.navigator.cookieEnabled};m.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');m.da(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,m.G)()+1E3*c)).toUTCString();this.j.cookie=a+"="+b+e+d+c+f};
m.g.get=function(a,b){for(var c=a+"=",d=(this.j.cookie||"").split(m.Ee),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};m.g.remove=function(a,b,c){var d=m.da(this.get(a));this.set(a,"",0,b,c);return d};m.g.sb=m.ba(4);m.g.Ya=m.ba(5);m.g.isEmpty=function(){return!this.j.cookie};m.g.Xa=m.ba(2);m.g.lf=m.ba(6);m.g.clear=function(){for(var a=m.De(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};m.Ge=new m.Ce(window.document);m.Ge.k=3950;Qe.prototype.get=function(){var a;0<this.k?(this.k--,a=this.j,this.j=a.next,a.next=null):a=this.l();return a};Qe.prototype.put=function(a){this.n(a);this.k<this.A&&(this.k++,a.next=this.j,this.j=a)};var af;var bf=new Qe(function(){return new Ue},function(a){a.reset()},100);Te.prototype.add=function(a,b){var c=bf.get();c.set(a,b);this.k?this.k.next=c:this.j=c;this.k=c};Te.prototype.remove=function(){var a=null;this.j&&(a=this.j,this.j=this.j.next,this.j||(this.k=null),a.next=null);return a};Ue.prototype.set=function(a,b){this.Ed=a;this.scope=b;this.next=null};Ue.prototype.reset=function(){this.next=this.scope=this.Ed=null};var We,Ye=!1,Ze=new Te;hf.prototype.reset=function(){this.context=this.k=this.l=this.j=null;this.n=!1};var kf=new Qe(function(){return new hf},function(a){a.reset()},100);m.ef.prototype.then=function(a,b,c){return m.tf(this,m.na(a)?a:null,m.na(b)?b:null,c)};m.cf(m.ef);m.ef.prototype.cancel=function(a){0==this.j&&Ve(function(){var b=new uf(a);pf(this,b)},this)};m.ef.prototype.J=function(a){this.j=0;gf(this,2,a)};m.ef.prototype.F=function(a){this.j=0;gf(this,3,a)};
m.ef.prototype.P=function(){for(var a=null;a=qf(this);)rf(this,a,this.j,this.C);this.B=!1};var xf=Re;m.t(uf,m.wa);uf.prototype.name="cancel";var Bf={};Df.prototype.l=function(a){Cf(this.j,"startFeedback",arguments)};Df.prototype.n=function(a){Cf(this.j,"startHelp",arguments)};Df.prototype.k=function(a){Cf(this.j,"loadChatSupport",arguments)};var pj=!1,qj="";
if(window.navigator.plugins&&window.navigator.plugins.length){var rj=window.navigator.plugins["Shockwave Flash"];rj&&(pj=!0,rj.description&&(qj=Ff(rj.description)));window.navigator.plugins["Shockwave Flash 2.0"]&&(pj=!0,qj="2.0.0.11")}else if(window.navigator.mimeTypes&&window.navigator.mimeTypes.length){var sj=window.navigator.mimeTypes["application/x-shockwave-flash"];(pj=sj&&sj.enabledPlugin)&&(qj=Ff(sj.enabledPlugin.description))}else try{var tj=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),pj=
!0,qj=Ff(tj.GetVariable("$version"))}catch(aaa){try{tj=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),pj=!0,qj="6.0.21"}catch(baa){try{tj=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash"),pj=!0,qj=Ff(tj.GetVariable("$version"))}catch(caa){}}}m.uj=pj;m.vj=qj;var yj;m.Kf=m.Ac("Firefox");m.wj=m.Gc()||m.Ac("iPod");m.xj=m.Ac("iPad");yj=m.Ac("Android")&&!(Ec()||m.Ac("Firefox")||Cc()||m.Ac("Silk"));m.Mf=Ec();m.Lf=m.Ac("Safari")&&!(Ec()||m.Ac("Coast")||Cc()||Dc()||m.Ac("Silk")||m.Ac("Android"))&&!(m.Gc()||m.Ac("iPad")||m.Ac("iPod"));var If=function(){if(m.Kf)return Gf(/Firefox\/([0-9.]+)/);if(m.D||m.Vf)return Nc;if(m.Mf)return Gf(/Chrome\/([0-9.]+)/);if(m.Lf&&!(m.Gc()||m.Ac("iPad")||m.Ac("iPod")))return Gf(/Version\/([0-9.]+)/);if(m.wj||m.xj){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(m.Bc))return a[1]+"."+a[2]}else if(yj)return(a=Gf(/Android\s+([0-9.]+)/))?a:Gf(/Version\/([0-9.]+)/);return""}();m.l("userfeedback.api.isBrowserSupportedForGenie",function(){return Jf()},void 0);m.l("userfeedback.api.isBrowserSupportedForHelp",Jf,void 0);m.ga(Nf);Nf.prototype.getVersion=function(){return[this.j,this.k,this.l]};m.g=m.Xf.prototype;m.g.getHeight=function(){return this.bottom-this.top};m.g.clone=function(){return new m.Xf(this.top,this.right,this.bottom,this.left)};m.g.contains=function(a){return m.Yf(this,a)};m.g.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
m.g.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};m.g.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};m.g.scale=function(a,b){var c=m.ma(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};var $f={};m.zj=m.kd(function(){if(m.D)return m.Lc("10.0");var a=window.document.createElement("DIV"),b=m.Wf(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");m.qc(a,m.gc("div",{style:c}));a=a.firstChild;b=a.style[m.Oa("transition")];return""!=("undefined"!==typeof b?b:a.style[m.Zf(a,"transition")]||"")});var jg;m.fg={};jg=!1;var Eg,Bj;m.Aj=!m.D||m.Oc(9);Eg=!m.D||m.Oc(9);Bj=m.D&&!m.Lc("9");!m.Jc||m.Lc("528");m.Ic&&m.Lc("1.9b")||m.D&&m.Lc("8")||m.Vf&&m.Lc("9.5")||m.Jc&&m.Lc("528");m.Ic&&!m.Lc("8")||m.D&&m.Lc("9");m.lg.prototype.stopPropagation=function(){this.Re=!0};m.lg.prototype.preventDefault=function(){this.defaultPrevented=!0;this.Hp=!1};m.Cj=m.D?"focusin":"DOMFocusIn";m.Dj=m.D?"focusout":"DOMFocusOut";m.Ej=m.Jc?"webkitTransitionEnd":m.Vf?"otransitionend":"transitionend";m.t(m.mg,m.lg);
m.mg.prototype.init=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;d?m.Ic&&(m.va(d,"nodeName")||(d=null)):"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=m.Jc||void 0!==a.offsetX?a.offsetX:a.layerX;this.offsetY=m.Jc||void 0!==a.offsetY?a.offsetY:a.layerY;this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=
a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.Wa=a;a.defaultPrevented&&this.preventDefault()};m.mg.prototype.stopPropagation=function(){m.mg.D.stopPropagation.call(this);this.Wa.stopPropagation?this.Wa.stopPropagation():this.Wa.cancelBubble=!0};
m.mg.prototype.preventDefault=function(){m.mg.D.preventDefault.call(this);var a=this.Wa;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Bj)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};m.mg.prototype.Nj=m.ba(7);var qg;m.og="closure_listenable_"+(1E6*Math.random()|0);qg=0;m.sg.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.j[f];a||(a=this.j[f]=[],this.k++);var h=m.ug(a,b,d,e);-1<h?(b=a[h],c||(b.mh=!1)):(b=new pg(b,this.src,f,!!d,e),b.mh=c,a.push(b));return b};m.sg.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.j))return!1;var e=this.j[a];b=m.ug(e,b,c,d);return-1<b?(rg(e[b]),m.Va(e,b),0==e.length&&(delete this.j[a],this.k--),!0):!1};
m.sg.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.j)if(!a||c==a){for(var d=this.j[c],e=0;e<d.length;e++)++b,rg(d[e]);delete this.j[c];this.k--}return b};var zg="closure_lm_"+(1E6*Math.random()|0),Gg={},Cg=0,Jg="__closure_events_fn_"+(1E9*Math.random()>>>0);m.ga(m.Kg);m.Lg=m.n("yt.prefs.UserPrefs.prefs_")||{};m.l("yt.prefs.UserPrefs.prefs_",m.Lg,void 0);m.g=m.Kg.prototype;m.g.get=function(a,b){Ng(a);Mg(a);var c=void 0!==m.Lg[a]?m.Lg[a].toString():null;return null!=c?c:b?b:""};m.g.set=function(a,b){Ng(a);Mg(a);if(null==b)throw"ExpectedNotNull";m.Lg[a]=b.toString()};m.g.remove=function(a){Ng(a);Mg(a);delete m.Lg[a]};m.g.save=function(){var a;a=[];for(var b in m.Lg)a.push(b+"="+(0,window.escape)(m.Lg[b]));a=a.join("&");m.Fe("PREF",a,63072E3)};
m.g.clear=function(){m.Lg={}};var Xg=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var Zg;var Fj=m.Bc,Fj=Fj.toLowerCase();if(m.Ia(Fj,"android")){var Gj=Fj.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(Gj)Zg=Number(Gj[1]);else{var Hj={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},Ij=Fj.match("("+m.Fb(Hj).join("|")+")");Zg=Ij?Hj[Ij[0]]:0}}else Zg=void 0;m.t(m.ah,$g);m.ah.prototype.Xa=m.ba(1);m.ah.prototype.clear=function(){var a=m.pd(this.Fb(!0)),b=this;(0,m.A)(a,function(a){b.remove(a)})};m.t(m.bh,m.ah);m.g=m.bh.prototype;m.g.isAvailable=function(){if(!this.j)return!1;try{return this.j.setItem("__sak","1"),this.j.removeItem("__sak"),!0}catch(a){return!1}};m.g.set=function(a,b){try{this.j.setItem(a,b)}catch(c){if(0==this.j.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};m.g.get=function(a){a=this.j.getItem(a);if(!m.ka(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};m.g.remove=function(a){this.j.removeItem(a)};
m.g.Xa=m.ba(0);m.g.Fb=function(a){var b=0,c=this.j,d=new m.ld;d.next=function(){if(b>=c.length)throw m.nd;var d;d=c.key(b++);if(a)return d;d=c.getItem(d);if(!m.ka(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};m.g.clear=function(){this.j.clear()};m.g.key=function(a){return this.j.key(a)};m.t(m.ch,m.bh);m.t(dh,m.bh);m.gh.prototype.yb=function(a){var b=[];hh(this,a,b);return b.join("")};var kh={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},jh=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;m.lh.prototype.set=function(a,b){m.da(b)?this.j.set(a,m.fh(b)):this.j.remove(a)};m.lh.prototype.get=function(a){var b;try{b=this.j.get(a)}catch(c){return}if(null!==b)try{return m.eh(b)}catch(d){throw"Storage: Invalid value was encountered";}};m.lh.prototype.remove=function(a){this.j.remove(a)};m.t(mh,m.lh);mh.prototype.set=function(a,b){mh.D.set.call(this,a,oh(b))};mh.prototype.k=function(a){a=mh.D.get.call(this,a);if(!m.da(a)||a instanceof Object)return a;throw"Storage: Invalid value was encountered";};mh.prototype.get=function(a){if(a=this.k(a)){if(a=a.data,!m.da(a))throw"Storage: Invalid value was encountered";}else a=void 0;return a};m.t(m.ph,mh);m.ph.prototype.set=function(a,b,c){if(b=oh(b)){if(c){if(c<(0,m.G)()){m.ph.prototype.remove.call(this,a);return}b.expiration=c}b.creation=(0,m.G)()}m.ph.D.set.call(this,a,b)};m.ph.prototype.k=function(a,b){var c=m.ph.D.k.call(this,a);if(c)if(!b&&m.qh(c))m.ph.prototype.remove.call(this,a);else return c};m.t(m.rh,m.ph);var Jj,Kj;Jj=new m.ch;m.th=Jj.isAvailable()?new m.rh(Jj):null;Kj=new dh;m.uh=Kj.isAvailable()?new m.rh(Kj):null;m.t(xh,m.u);m.g=xh.prototype;m.g.getId=function(){return this.S};m.g.Hl=function(a,b){this.Na()||(zh(this,a),Fh(this,b),this.P&&Bh(this))};m.g.Js=function(){return this.Eb};
m.g.SA=function(){if(!this.Fa){var a=Gh(this);if(a&&"html5"==Jh(this))this.J="html5",this.P||this.Lf();else if(Kh(this),this.J="html5",a&&this.vb)this.B.appendChild(this.vb),this.Lf();else{this.j.loaded=!0;var b=(0,m.q)(function(){var a=this.B,b=this.j.clone();m.n("yt.player.Application.create")(a,b);this.Lf()},this);this.C=b;this.Fa=!0;a?this.C():(this.j.assets.js2?(this.C=a=(0,m.q)(function(){m.uc(this.j.assets.js2,b);this.C=b},this),m.uc(this.j.assets.js,a)):m.uc(this.j.assets.js,this.C),m.Wg(this.j.assets.css))}}};
m.g.RA=function(){var a=this.j.clone();if(!this.F){var b=Eh(this);b&&(this.F=window.document.createElement("span"),this.F.tabIndex=0,this.mb.push(m.K(this.F,"focus",(0,m.q)(this.Oo,this))),this.R=window.document.createElement("span"),this.R.tabIndex=0,this.mb.push(m.K(this.R,"focus",(0,m.q)(this.Oo,this))),m.cd(this.F,b),m.dd(this.R,b))}a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==Jh(this)?(this.J="flash",this.P||Ug(a,!1,(0,m.q)(this.Lf,this))):(Kh(this),this.J=
"flash",this.j.loaded=!0,m.Rg(this.B,a),this.Lf())};m.g.Oo=function(){Eh(this).focus()};
m.g.Lf=function(){if(!this.Na()){var a=Eh(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(c){}if(b)if(this.Fa=!1,a.isNotServable&&a.isNotServable(this.j.args.video_id))Dh(this);else{yh(this);this.P=!0;a=Eh(this);a.addEventListener&&(this.O=Hh(this,a,"addEventListener"));a.removeEventListener&&(this.$a=Hh(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),d=0;d<b.length;d++){var e=b[d];this.k[e]||(this.k[e]=Hh(this,a,e))}for(var f in this.A)this.O(f,
this.A[f]);Bh(this);this.ab&&this.ab(this.k);this.ga.W("onReady",this.k);a.apiProxyReady&&a.apiProxyReady()}else this.ic=m.x((0,m.q)(this.Lf,this),50)}};m.g.eB=function(){return this.P};m.g.nd=function(a,b){if(!this.Na()){var c=Ah(this,b);if(c){if(!m.Sa(this.rd,a)&&!this.A[a]){var d=Ih(this,a);this.O&&this.O(a,d)}this.ga.subscribe(a,c);"onReady"==a&&this.P&&m.x(m.r(c,this.k),0)}}};m.g.Qz=function(a,b){if(!this.Na()){var c=Ah(this,b);c&&this.ga.Ye(a,c)}};
m.g.as=function(a){a=a?fd:ed;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||b==this.F||b==this.R||(b.focus(),b!=window.document.activeElement));)b=a(b)};m.g.yA=function(a){m.B("a11y-announce",a)};m.g.ky=function(a){var b={};b.volume=(0,window.isNaN)(a.volume)?wh().volume:m.yc(a.volume,0,100);b.muted=void 0==a.muted?wh().muted:a.muted;m.sh("yt-player-volume",b,2592E3)};m.g.iy=function(a){5==a&&Dh(this)};m.g.ly=function(a){m.B("WATCH_LATER_VIDEO_ADDED",a)};
m.g.my=function(a){m.B("WATCH_LATER_VIDEO_REMOVED",a)};m.g.Yx=function(a){if(!m.gd(this.B,m.Be(a)))this.k.onExternalMouseMove()};m.g.Xx=function(){m.vg(window.document,"mousemove",this.Yx,!1,this)};m.g.Zx=function(){this.Hc&&(this.ub||(this.Ra=m.Uc(window.document)),this.U||(this.U=m.vg(window,"scroll",this.sz,!1,this)));this.ub=!0};m.g.$x=function(){this.U&&(m.Fg(this.U),this.U=null);this.ub=!1};m.g.To=function(a){this.ub&&!this.Hc&&a.preventDefault()};
m.g.sz=function(){this.Ra&&window.scrollTo(this.Ra.x,this.Ra.y)};
m.g.TA=function(){Kh(this);this.J="unsupported";var a='Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>',b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a='Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/"> Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>');b=
this.j.messages.player_fallback||a;a=m.E("player-unavailable");m.E("unavailable-submessage")&&a&&(m.E("unavailable-submessage").innerHTML=b,(b=m.F("icon",a))&&m.sc(b,"icon")&&(b.src=m.C(b,"icon")),m.J(a,"hid"),m.I(m.E("player"),"off-screen-trigger"))};m.g.Ls=function(){return this.J||Jh(this)};m.g.Ks=function(){return this.Lb};m.g.cancel=function(){if(this.C){var a=this.C,b=m.vc(this.j.assets.js);window.spf.script.ignore(b,a)}m.gb(this.ic);this.Fa=!1};
m.g.L=function(){Kh(this);this.ib=null;for(var a in this.A)m.ea[this.A[a]]=null;this.k=null;delete this.B;delete this.n;this.j&&(this.Eb=this.j=this.j.fallback=null);xh.D.L.call(this)};var Nh={},Mh="player_uid_"+(1E9*Math.random()>>>0);var Lj=m.n("yt.abuse.botguardInitialized")||se;m.l("yt.abuse.botguardInitialized",Lj,void 0);var Mj=m.n("yt.abuse.invokeBotguard")||m.ue;m.l("yt.abuse.invokeBotguard",Mj,void 0);var Nj=m.n("yt.player.exports.navigate")||m.Pe;m.l("yt.player.exports.navigate",Nj,void 0);var Oj=m.n("yt.player.embed")||m.Lh;m.l("yt.player.embed",Oj,void 0);var Pj=m.n("yt.player.destroy")||m.Qh;m.l("yt.player.destroy",Pj,void 0);var Qj=m.n("yt.player.cancelAll")||Ph;m.l("yt.player.cancelAll",Qj,void 0);
var Rj=m.n("yt.player.getPlayerByElement")||m.Rh;m.l("yt.player.getPlayerByElement",Rj,void 0);var Sj=m.n("yt.player.exports.feedbackStart")||m.hg;m.l("yt.player.exports.feedbackStart",Sj,void 0);var Tj=m.n("yt.player.exports.feedbackShowArticle")||m.kg;m.l("yt.player.exports.feedbackShowArticle",Tj,void 0);var Uj=m.n("yt.util.activity.init")||m.Ie;m.l("yt.util.activity.init",Uj,void 0);var Vj=m.n("yt.util.activity.getTimeSinceActive")||m.Ke;m.l("yt.util.activity.getTimeSinceActive",Vj,void 0);
var Wj=m.n("yt.util.activity.setTimestamp")||Je;m.l("yt.util.activity.setTimestamp",Wj,void 0);var Vh,$h;m.Zh=null;$h="";var ci=[];var ii,Di,Ci,ji,li,ti,ni,pi,wi;ji=0;li=[900,60,"waiting"];ti=[500,99,"waiting"];ni=[300,60,"waiting"];pi=[400,99,"waiting"];wi=[300,101,"done"];window.yt=window.yt||{};m.l("yt.setConfig",m.bb,void 0);m.l("yt.getConfig",m.w,void 0);m.l("yt.hasMsg",m.jb,void 0);m.l("yt.pubsub.publish",m.B,void 0);m.l("yt.pubsub.subscribe",m.z,void 0);m.l("yt.setMsg",function(a){cb(m.kb,arguments)},void 0);m.l("yt.setGoogMsg",function(a){cb(m.kb,arguments)},void 0);m.l("yt.timing.report",de,void 0);
m.l("yt.timing.reportAdToVideo",function(a,b,c){c={v:2,s:"youtube",action:c?"watch,ad2video_html5":"watch,ad2video"};a.aft=a.pbs=a.astv||a.actv;var d=[],e;for(e in a)"_"!=e.charAt(0)&&d.push(e+"."+a[e]);c.rt=d.join(",");for(var f in b)"_"!=f.charAt(0)&&(c[f]=b[f]);a=m.w("TIMING_INFO")||{};"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);ae(c)},void 0);m.l("ytcsi.tick",m.Ld,void 0);m.t(Ei,m.yb);
Ei.prototype.enable=function(){window.onload=ei;window.onunload=fi;window.onerror=gi;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfrequest",hi),window.addEventListener("spfpartprocess",mi),window.addEventListener("spfpartdone",ri),window.addEventListener("spfprocess",si),window.addEventListener("spfdone",ui),window.addEventListener("spferror",xi),window.addEventListener("spfreload",yi),window.addEventListener("spfjsbeforeunload",Fi)),a.config=a.config||{},
window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",zi),this.subscribe("dispose",Bi)):window.spf.dispose();this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
Ei.prototype.init=function(){Ei.D.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&m.w("PAGEFRAME_JS")?(b=m.w("PAGEFRAME_JS"),c=function(){window.ytPageFrameLoaded=!0;m.n("ytbin.www.pageframe.setup")()}):a&&(a=m.n("yt.www.masthead.loadSearchbox"))&&a();var a=m.w("JS_COMMON_MODULE"),d=m.w("JS_PAGE_MODULES");d||(d=[a]);a=m.w("JS_DELAY_LOAD",void 0);0<a?(m.gb(this.l),this.l=m.x(function(){b&&m.uc(b,c);window.spf.script.require(d)},a)):(b&&m.uc(b,
c),window.spf.script.require(d));Th();var a=!!m.n("yt.reactLoaded"),e=m.w("REACT_JS");!a&&e&&m.uc(e,function(){m.l("yt.reactLoaded",!0,void 0)})};Ei.prototype.dispose=function(){m.gb(this.l);var a=m.n("ytbin.www.pageframe.cancelSetup");a&&a();m.hb(Vh);if(a=m.Xh())a.removeEventListener("onReady",Wh),a.removeEventListener("onStateChange",Wh);Ei.D.dispose.call(this)};
Ei.prototype.disable=function(){Ei.D.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfrequest",hi),window.removeEventListener("spfpartprocess",mi),window.removeEventListener("spfpartdone",ri),window.removeEventListener("spfprocess",si),window.removeEventListener("spfdone",ui),window.removeEventListener("spferror",xi),window.removeEventListener("spfreload",yi),window.removeEventListener("spfjsbeforeunload",Fi));window.onload=null;window.onunload=null;window.onerror=null};
m.Ab(new Ei);})(_yt_www);
